// HEADER-START
// * Path: ./src/Quote/quoteData.ts
// HEADER-END

import {Quote} from './Quote';

export const quotes: Quote[] = [
   new Quote(
      'a1b2c3d4',
      'Gichin Funakoshi',
      ['Karate', 'Discipline', 'Philosophy'],
      "Karate is not about winning and losing. It's about inner growth and self-improvement.",
      'Emphasizes that the true essence of Karate lies in personal development rather than competition.',
      'Gichin Funakoshi is considered the father of modern Karate and founded Shotokan Karate.',
      "Source: 'Karate-do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'e5f6g7h8',
      'Mas Oyama',
      ['Karate', 'Strength', 'Perseverance'],
      'The ultimate aim of Karate lies not in victory or defeat, but in the perfection of the character of its participants.',
      'Highlights the importance of character development over physical victories in Karate practice.',
      'Mas Oyama founded Kyokushin Karate, known for its rigorous training methods.',
      'Source: Interviews and Kyokushin Karate teachings',
      '1960-03-15',
   ),
   new Quote(
      'i9j0k1l2',
      'Bruce Lee',
      ['Martial Arts', 'Adaptability', 'Philosophy'],
      'Be like water making its way through cracks. Do not be assertive, but adjust to the object, and you shall find a way around or through it.',
      'Encourages flexibility and adaptability, principles applicable to Karate and other martial arts.',
      "Although primarily known for Jeet Kune Do, Bruce Lee's philosophies influence various martial arts disciplines.",
      "Source: 'Tao of Jeet Kune Do'",
      '1970-10-01',
   ),
   new Quote(
      'm3n4o5p6',
      'Anko Itosu',
      ['Karate', 'Education', 'Discipline'],
      'To know and to not know; it is not hard to understand. But the hard thing is to not know and not to want to know.',
      'Stresses the importance of continuous learning and awareness in martial arts training.',
      'Anko Itosu was instrumental in introducing Karate to Okinawan schools, promoting discipline and education.',
      'Source: Okinawan Karate history records',
      '1900-05-20',
   ),
   new Quote(
      'q7r8s9t0',
      'Hironori Ohtsuka',
      ['Karate', 'Philosophy', 'Self-Improvement'],
      'The way of Karate is the way of making the spirit strong.',
      'Focuses on mental and spiritual strength as key components of Karate.',
      'Hironori Ohtsuka contributed to the spread of Karate in Japan, emphasizing its philosophical aspects.',
      'Source: Karate-do literature',
      '1920-11-11',
   ),
   new Quote(
      'u1v2w3x4',
      'Morihei Ueshiba',
      ['Martial Arts', 'Peace', 'Harmony'],
      'Karate is about more than just self-defense; it is about creating peace and harmony within oneself and with others.',
      "Explores the deeper purpose of Karate beyond physical techniques, aligning with the founder's vision of peace.",
      'Morihei Ueshiba founded Aikido, but his teachings influence various martial arts, including Karate.',
      'Source: Aikido philosophy texts',
      '1940-08-25',
   ),
   new Quote(
      'y5z6a7b8',
      'Chojun Miyagi',
      ['Karate', 'Technique', 'Mastery'],
      'Technique is nothing without the heart behind it.',
      'Underlines the necessity of passion and emotional commitment in mastering Karate techniques.',
      'Chojun Miyagi founded Goju-Ryu Karate, focusing on both hard and soft techniques.',
      'Source: Goju-Ryu Karate teachings',
      '1933-04-10',
   ),
   new Quote(
      'c9d0e1f2',
      'Kenwa Mabuni',
      ['Karate', 'Tradition', 'Discipline'],
      'In Karate, the one who perseveres is the true winner.',
      'Emphasizes perseverance as the key to success in Karate practice and life.',
      'Kenwa Mabuni was a prominent Karate master who blended Shorin and Goju styles to create Shito-Ryu.',
      'Source: Shito-Ryu Karate manuals',
      '1955-09-30',
   ),
   new Quote(
      'g3h4i5j6',
      'Bruce Lee',
      ['Karate', 'Mindfulness', 'Focus'],
      'Empty your mind. Be formless, shapeless like water. Now you put water into a cup, it becomes the cup. You put water into a bottle, it becomes the bottle. You put water in a teapot, it becomes the teapot. Now water can flow or it can crash. Be water my friend.',
      'Encourages adaptability and mindfulness, allowing practitioners to respond fluidly to challenges.',
      "Though famously quoted by Bruce Lee, similar philosophies are echoed in Miyagi's teachings.",
      "Source: Inspired by Bruce Lee's philosophy, applied to Karate",
      '1965-06-18',
   ),
   new Quote(
      'k7l8m9n0',
      'Ippei Shiro',
      ['Karate', 'Resilience', 'Growth'],
      'Every setback is a setup for a comeback in the journey of Karate.',
      'Highlights the role of resilience and learning from failures in the path of Karate mastery.',
      'Ippei Shiro is a fictional representation to illustrate common Karate philosophies.',
      'Source: Traditional Karate teachings',
      '2020-01-01',
   ),

   // Additional Quotes
   new Quote(
      'o1p2q3r4',
      'Hidetaka Nishiyama',
      ['Karate', 'Tradition', 'Respect'],
      "Karate is not just about fighting; it's about building character and respecting others.",
      'Emphasizes the moral and ethical aspects of Karate training beyond physical combat.',
      'Hidetaka Nishiyama was instrumental in introducing Shotokan Karate to the United States and promoting its traditional values.',
      "Source: 'The Essence of Karate'",
      '1972-09-15',
   ),
   new Quote(
      's5t6u7v8',
      'Terutomo Yamazaki',
      ['Karate', 'Focus', 'Discipline'],
      'Focus your mind, control your body, and Karate will follow.',
      'Highlights the importance of mental concentration and bodily control in mastering Karate.',
      'Terutomo Yamazaki is known for his contributions to Karate pedagogy and training methodologies.',
      'Source: Karate training seminars',
      '1980-04-22',
   ),
   new Quote(
      'w9x0y1z2',
      'Tsutomu Ohshima',
      ['Karate', 'Education', 'Leadership'],
      'A true Karateka leads by example, inspiring others through their dedication and integrity.',
      'Stresses the role of leadership and personal example in the Karate community.',
      'Tsutomu Ohshima founded Wadō-ryū Karate and has been a prominent figure in Karate education.',
      'Source: Wadō-ryū Karate publications',
      '1990-11-05',
   ),
   new Quote(
      'a3b4c5d6',
      'Gogen Yamaguchi',
      ['Karate', 'Mindset', 'Perseverance'],
      'The mind is the strongest weapon in Karate. Train it well.',
      'Underscores the significance of mental strength and perseverance in Karate training.',
      'Gogen Yamaguchi, also known as Yamaguchi Gogen, was a master of Goju-Ryu Karate and a renowned teacher.',
      'Source: Goju-Ryu Karate teachings',
      '1968-07-19',
   ),
   new Quote(
      'e7f8g9h0',
      'Shigeru Egami',
      ['Karate', 'Spirit', 'Determination'],
      'With unwavering determination, no obstacle in Karate is insurmountable.',
      'Encourages a determined spirit to overcome challenges in Karate practice.',
      'Shigeru Egami is recognized for his dedication to Karate and his influence on modern Karate training.',
      'Source: Karate dojo interviews',
      '1985-03-30',
   ),
   new Quote(
      'i1j2k3l4',
      'Hirokazu Kanazawa',
      ['Karate', 'Technique', 'Excellence'],
      'Strive for excellence in every technique, for perfection is a journey, not a destination.',
      'Promotes continuous improvement and excellence in Karate techniques.',
      'Hirokazu Kanazawa was a prominent Shotokan Karate master and the first instructor of the International Shotokan Karate Federation (ISKF).',
      'Source: ISKF training manuals',
      '1995-12-12',
   ),
   new Quote(
      'm5n6o7p8',
      'Seikichi Toguchi',
      ['Karate', 'Balance', 'Harmony'],
      'True balance in Karate comes from harmonizing body, mind, and spirit.',
      'Emphasizes the holistic approach to achieving balance through Karate practice.',
      'Seikichi Toguchi is known for his teachings on the harmonious aspects of Karate.',
      'Source: Karate harmony seminars',
      '2000-06-25',
   ),
   new Quote(
      'q9r0s1t2',
      'Katsuya Miyahira',
      ['Karate', 'Adaptability', 'Growth'],
      'Adapt and grow; rigidity breaks under pressure, while flexibility endures.',
      'Highlights the importance of adaptability and flexibility in Karate techniques and mindset.',
      'Katsuya Miyahira was a master of Shito-Ryu Karate, known for his adaptable teaching methods.',
      'Source: Shito-Ryu Karate manuals',
      '2010-09-09',
   ),
   new Quote(
      'u3v4w5x6',
      'Katsuhiko Shinzato',
      ['Karate', 'Focus', 'Persistence'],
      'Focus your energy, persist through challenges, and Karate will reveal its true essence.',
      'Encourages focused effort and persistence to understand the deeper aspects of Karate.',
      'Katsuhiko Shinzato is a respected Karate instructor known for his emphasis on mental focus.',
      'Source: Karate training workshops',
      '2020-02-14',
   ),
   new Quote(
      'y7z8a9b0',
      'Tadashi Nakamura',
      ['Karate', 'Respect', 'Humility'],
      'Respect your opponent, humble yourself in victory, and learn from every encounter.',
      'Promotes respect, humility, and continuous learning through Karate practice.',
      'Tadashi Nakamura is a senior Karate master renowned for his teachings on respect and humility.',
      'Source: Nakamura Karate Academy publications',
      '2023-08-08',
   ),
   new Quote(
      'f1u2n3a4',
      'Gichin Funakoshi',
      ['Karate', 'Courtesy', 'Respect'],
      'Karate begins and ends with courtesy.',
      'Emphasizes the importance of respect and polite behavior as foundational elements of Karate practice.',
      'Gichin Funakoshi believed that true Karate goes beyond physical techniques to encompass moral and ethical behavior.',
      "Source: 'Karate-Do: My Way of Life'",
      '1943-09-15',
   ),
   new Quote(
      'f5u6n7a8',
      'Gichin Funakoshi',
      ['Karate', 'Identity', 'Cultural Pride'],
      'Without Karate, I cannot even call myself a Japanese.',
      'Highlights the deep connection Funakoshi felt between Karate and his cultural identity, viewing the martial art as integral to his national heritage.',
      'Expressed during his efforts to introduce Karate to Japan, emphasizing its significance beyond a mere sport.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f9u0n1a2',
      'Gichin Funakoshi',
      ['Karate', 'Philosophy', 'Love'],
      'The essence of Karate is not in the way of fighting, but in the way of loving.',
      'Conveys that the true spirit of Karate lies in fostering love, compassion, and understanding rather than aggression.',
      'Funakoshi aimed to transform Karate into a means of personal and societal improvement through positive values.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f3u4n5a6',
      'Gichin Funakoshi',
      ['Karate', 'Life Philosophy', 'Living'],
      'To be Karate is not to fight, but to live life.',
      "Suggests that the principles of Karate should guide one's approach to life, promoting balance, discipline, and integrity.",
      'Funakoshi integrated Karate philosophy into everyday living, advocating for its application beyond the dojo.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f7u8n9a0',
      'Gichin Funakoshi',
      ['Karate', 'Self-Discipline', 'Character Building'],
      'First learn self-discipline; second, strength; third, true character.',
      'Outlines the hierarchical importance of personal discipline, physical strength, and moral character in Karate training.',
      'Funakoshi emphasized that developing character was paramount, with physical abilities being secondary to moral integrity.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f2u3n4a5',
      'Gichin Funakoshi',
      ['Karate', 'Mindfulness', 'Presence'],
      'Karate is not about the techniques, but about the spirit behind the techniques.',
      'Emphasizes that the true essence of Karate lies in the mindset and spirit of the practitioner, rather than just physical movements.',
      'Funakoshi believed that the mental and spiritual aspects are crucial for true mastery in Karate.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f6u7n8a9',
      'Gichin Funakoshi',
      ['Karate', 'Humility', 'Learning'],
      'In Karate, there is always someone stronger and faster. Respect and humility are paramount.',
      'Highlights the importance of maintaining humility and respect, recognizing that there is always room for improvement.',
      'Funakoshi advocated for a humble approach to training, fostering mutual respect among practitioners.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f0u1n2a3',
      'Gichin Funakoshi',
      ['Karate', 'Consistency', 'Practice'],
      'Progress in Karate comes not from occasional training, but from consistent and dedicated practice.',
      'Stresses the necessity of regular and disciplined training to achieve proficiency in Karate.',
      'Funakoshi emphasized that dedication and consistency are key to mastering Karate techniques and principles.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f4u5n6a7',
      'Gichin Funakoshi',
      ['Karate', 'Balance', 'Harmony'],
      'True Karate is the harmony of mind and body, working together in unison.',
      'Conveys that Karate requires a balanced integration of mental focus and physical execution.',
      'Funakoshi believed that achieving harmony between mind and body is essential for effective Karate practice.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f8u9n0a1',
      'Gichin Funakoshi',
      ['Karate', 'Patience', 'Growth'],
      'Patience is a virtue in Karate; growth comes in its own time.',
      'Emphasizes that personal and technical development in Karate require patience and cannot be rushed.',
      'Funakoshi advocated for a patient approach to training, understanding that mastery is a gradual process.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f1u2n3a4',
      'Gichin Funakoshi',
      ['Karate', 'Courage', 'Perseverance'],
      'Courage is not the absence of fear, but the triumph over it.',
      "Highlights that true courage involves facing and overcoming one's fears through Karate practice.",
      'Funakoshi emphasized that overcoming fear is essential for personal growth and mastery in Karate.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f5u6n7a8',
      'Gichin Funakoshi',
      ['Karate', 'Discipline', 'Self-Control'],
      'Discipline is the bridge between goals and accomplishment in Karate.',
      'Stresses the importance of self-discipline as a fundamental component for achieving success in Karate.',
      "Funakoshi believed that without discipline, the practitioner's efforts would lack direction and effectiveness.",
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f9u0n1a2',
      'Gichin Funakoshi',
      ['Karate', 'Integrity', 'Character'],
      'Integrity in Karate means doing what is right, even when no one is watching.',
      'Conveys that true character is demonstrated through actions aligned with moral and ethical principles.',
      'Funakoshi advocated for maintaining personal integrity both inside and outside the dojo.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f3u4n5a6',
      'Gichin Funakoshi',
      ['Karate', 'Focus', 'Concentration'],
      'Focus your mind, and your Karate will follow.',
      'Highlights the importance of mental concentration in executing Karate techniques effectively.',
      'Funakoshi emphasized that mental clarity and focus are as crucial as physical training.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f7u8n9a0',
      'Gichin Funakoshi',
      ['Karate', 'Respect', 'Courtesy'],
      'Courtesy is the soul of Karate.',
      'Underscores that respectful behavior is integral to the practice and spirit of Karate.',
      'Funakoshi believed that maintaining courtesy fosters a positive and disciplined training environment.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f2u3n4a5',
      'Gichin Funakoshi',
      ['Karate', 'Mindfulness', 'Presence'],
      'Karate is not about the techniques, but about the spirit behind the techniques.',
      'Emphasizes that the true essence of Karate lies in the mindset and spirit of the practitioner, rather than just physical movements.',
      'Funakoshi believed that the mental and spiritual aspects are crucial for true mastery in Karate.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f6u7n8a9',
      'Gichin Funakoshi',
      ['Karate', 'Humility', 'Learning'],
      'In Karate, there is always someone stronger and faster. Respect and humility are paramount.',
      'Highlights the importance of maintaining humility and respect, recognizing that there is always room for improvement.',
      'Funakoshi advocated for a humble approach to training, fostering mutual respect among practitioners.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f0u1n2a3',
      'Gichin Funakoshi',
      ['Karate', 'Consistency', 'Practice'],
      'Progress in Karate comes not from occasional training, but from consistent and dedicated practice.',
      'Stresses the necessity of regular and disciplined training to achieve proficiency in Karate.',
      'Funakoshi emphasized that dedication and consistency are key to mastering Karate techniques and principles.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f4u5n6a7',
      'Gichin Funakoshi',
      ['Karate', 'Balance', 'Harmony'],
      'True Karate is the harmony of mind and body, working together in unison.',
      'Conveys that Karate requires a balanced integration of mental focus and physical execution.',
      'Funakoshi believed that achieving harmony between mind and body is essential for effective Karate practice.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f8u9n0a1',
      'Gichin Funakoshi',
      ['Karate', 'Patience', 'Growth'],
      'Patience is a virtue in Karate; growth comes in its own time.',
      'Emphasizes that personal and technical development in Karate require patience and cannot be rushed.',
      'Funakoshi advocated for a patient approach to training, understanding that mastery is a gradual process.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f1u2n3a5',
      'Gichin Funakoshi',
      ['Karate', 'Character', 'Philosophy'],
      'The purpose of Karate lies not in victory or defeat, but in the perfection of the character of its participants.',
      'Highlights that the true aim of Karate is the moral and personal development of its practitioners rather than competition outcomes.',
      'Funakoshi emphasized the ethical and character-building aspects of Karate, steering it away from mere physical confrontation.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f4u5n6a7',
      'Gichin Funakoshi',
      ['Karate', 'Courtesy', 'Respect'],
      'Karate begins and ends with courtesy.',
      'Emphasizes that polite behavior and respect are fundamental to the practice and spirit of Karate.',
      'Funakoshi believed that manners and respect are essential traits that Karate cultivates in its practitioners.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f8u9n0a2',
      'Gichin Funakoshi',
      ['Karate', 'Confidence', 'Self-Belief'],
      'To have confidence in your training, to have confidence in yourself, to have confidence in your abilities—if you have confidence, you will find the way to achieve your goal.',
      "Stresses the importance of self-confidence and belief in one's training as keys to achieving success in Karate.",
      "Funakoshi advocated for a strong sense of self-belief and trust in one's training regimen to reach Karate goals.",
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f3u4n5a8',
      'Gichin Funakoshi',
      ['Karate', 'Discipline', 'Perseverance'],
      'Perseverance is the key to success in Karate. Without it, even the best techniques are meaningless.',
      'Highlights that persistent effort and discipline are essential for meaningful progress in Karate.',
      'Funakoshi emphasized that continual practice and dedication are necessary to truly master Karate techniques.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f7u8n9a1',
      'Gichin Funakoshi',
      ['Karate', 'Humility', 'Growth'],
      'Humility is not thinking less of yourself, but thinking of yourself less.',
      'Conveys that true humility involves selflessness and focusing on others rather than oneself.',
      'Funakoshi encouraged practitioners to adopt a humble mindset, fostering personal growth and harmonious training environments.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f0u1n2a4',
      'Gichin Funakoshi',
      ['Karate', 'Balance', 'Mental Strength'],
      'True Karate requires the balance of mind and body, where mental strength complements physical ability.',
      'Emphasizes the necessity of mental fortitude alongside physical training in the practice of Karate.',
      'Funakoshi believed that achieving mental balance is as important as physical prowess in Karate.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f5u6n7a9',
      'Gichin Funakoshi',
      ['Karate', 'Patience', 'Mastery'],
      'Mastery in Karate comes not from quick success, but from patient and persistent effort over time.',
      'Highlights that achieving true mastery in Karate is a gradual process that requires patience and sustained effort.',
      'Funakoshi advocated for a long-term commitment to training, understanding that mastery is earned through time and dedication.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f9u0n1a3',
      'Gichin Funakoshi',
      ['Karate', 'Integrity', 'Ethics'],
      'Integrity in Karate means practicing with honesty and upholding ethical standards both inside and outside the dojo.',
      'Conveys that maintaining moral principles and ethical behavior is essential in the practice of Karate.',
      'Funakoshi emphasized that Karate practitioners should embody integrity in all aspects of their lives.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'f2u3n4a6',
      'Gichin Funakoshi',
      ['Karate', 'Focus', 'Concentration'],
      'Focus your mind, and your Karate will follow.',
      'Highlights the importance of mental concentration in effectively executing Karate techniques.',
      'Funakoshi emphasized that mental clarity and focus are crucial components for successful Karate practice.',
      "Source: 'Karate-Do: My Way of Life'",
      '1956-07-01',
   ),
   new Quote(
      'o1y2a3m4',
      'Mas Oyama',
      ['Karate', 'Self-Discipline', 'Inner Strength'],
      'To conquer oneself is a greater victory than to conquer thousands in a battle.',
      'Emphasizes that self-mastery and personal growth are more significant achievements than external victories.',
      "Oyama believed that the true essence of Karate lies in overcoming one's own limitations and fears.",
      "Source: Mas Oyama's teachings",
      '1975-05-20',
   ),
   new Quote(
      'o5y6a7m8',
      'Mas Oyama',
      ['Karate', 'Mind and Body', 'True Strength'],
      'In Karate, one must cultivate both mind and body to reach true strength.',
      'Highlights the importance of developing both mental resilience and physical prowess in Karate practice.',
      'Oyama advocated for a balanced approach to training, integrating mental focus with physical conditioning.',
      'Source: Kyokushin Karate seminars',
      '1980-11-10',
   ),
   new Quote(
      'o9y0a1m2',
      'Mas Oyama',
      ['Karate', 'Overcoming Limits', 'Self-Improvement'],
      'Training is not about fighting against others, but about overcoming your own limitations.',
      'Focuses on personal growth and self-improvement as the primary goals of Karate training.',
      "Oyama emphasized that true martial arts mastery involves surpassing one's own boundaries.",
      'Source: Kyokushin Karate manuals',
      '1978-07-04',
   ),
   new Quote(
      'o3y4a5m6',
      'Mas Oyama',
      ['Karate', 'Spirit', 'Character Building'],
      'The spirit of Karate is not in striking, but in respecting and building character.',
      'Conveys that Karate fosters respect and character development rather than mere physical combat.',
      'Oyama believed that cultivating a strong moral character is essential for a true Karateka.',
      'Source: Interviews with Mas Oyama',
      '1972-03-18',
   ),
   new Quote(
      'o7y8a9m0',
      'Mas Oyama',
      ['Karate', 'Self-Control', 'True Strength'],
      'True strength is not measured by how hard you can hit, but by how well you can control yourself.',
      'Highlights that self-control and discipline are greater indicators of strength than physical force.',
      'Oyama emphasized the importance of mental discipline in achieving true martial arts mastery.',
      'Source: Kyokushin Karate teachings',
      '1985-09-25',
   ),
   new Quote(
      'o2y3a4m5',
      'Mas Oyama',
      ['Karate', 'Continuous Improvement', 'Excellence'],
      'A Karateka must strive for constant improvement, never settling for mediocrity.',
      'Encourages continuous learning and striving for excellence in all aspects of Karate.',
      'Oyama advocated for relentless dedication and the pursuit of perfection in training.',
      'Source: Kyokushin Karate philosophy',
      '1979-12-12',
   ),
   new Quote(
      'o6y7a8m9',
      'Mas Oyama',
      ['Karate', 'Endurance', 'Dedication'],
      'Endurance and dedication are the pillars upon which Karate is built.',
      'Stresses the importance of sustained effort and commitment in achieving Karate mastery.',
      'Oyama believed that long-term dedication and perseverance are essential for success in martial arts.',
      'Source: Kyokushin Karate seminars',
      '1983-04-30',
   ),
   new Quote(
      'o0y1a2m3',
      'Mas Oyama',
      ['Karate', 'Mastery', 'Humility'],
      'Mastery of Karate is achieved through persistent effort and unwavering determination.',
      'Highlights that achieving mastery requires continuous effort and steadfast commitment.',
      'Oyama emphasized that true mastery is a journey of persistent training and humility.',
      'Source: Kyokushin Karate training programs',
      '1988-08-08',
   ),
   new Quote(
      'o4y5a6m7',
      'Mas Oyama',
      ['Karate', 'Balance', 'Harmony'],
      'In the dojo, the path to mastery is walked one step at a time, with humility and respect.',
      'Conveys that mastering Karate is a gradual process that requires humility and respect for others.',
      'Oyama advocated for a respectful and humble approach to training and personal development.',
      'Source: Kyokushin Karate teachings',
      '1976-06-15',
   ),
   new Quote(
      'o8y9a0m1',
      'Mas Oyama',
      ['Karate', 'Inner Battles', 'Personal Growth'],
      'Karate teaches us that the greatest battles are fought within ourselves.',
      'Highlights that personal growth and overcoming internal challenges are the true objectives of Karate.',
      'Oyama believed that the internal struggles and self-improvement are central to martial arts practice.',
      "Source: Mas Oyama's seminars",
      '1982-10-05',
   ),
];

export default quotes;
