// File: ./src/app/privacy/PrivacyPolicyPage.tsx

import { Box, Container, Divider, Paper, Typography, useTheme } from '@mui/material';
import React from 'react';

type PolicySection = {
  title: string;
  paragraphs: string[];
  bullets?: string[];
};

const POLICY_SECTIONS: PolicySection[] = [
  {
    title: 'Overview',
    paragraphs: [
      'Kyokushin-Kai is built to support your training journey. This policy explains what data we collect, how we use it, and the choices you have.',
      'By using the app, you agree to the practices described here. If you do not agree, please discontinue use.',
    ],
  },
  {
    title: 'Information We Collect',
    paragraphs: ['We collect information you provide and data generated by using the app.'],
    bullets: [
      'Account details such as name, email, and profile image when you register or sign in.',
      'Training data you log, including sessions, techniques, cards, and progress.',
      'Usage data such as pages visited, actions taken, and device or browser details.',
      'Feedback or support messages you submit through the app.',
    ],
  },
  {
    title: 'How We Use Information',
    paragraphs: ['We use your data to operate and improve the app. This includes:'],
    bullets: [
      'Providing core features like training trackers, saved progress, and personalized content.',
      'Authenticating your account and keeping your settings consistent across devices.',
      'Diagnosing bugs, monitoring performance, and improving reliability.',
      'Responding to feedback and support requests.',
    ],
  },
  {
    title: 'Sharing and Disclosure',
    paragraphs: [
      'We do not sell your personal data. We only share data when it is required to provide the service or comply with legal obligations.',
      'If you choose social sign-in, the provider may share basic profile information according to your settings with that provider.',
    ],
    bullets: [
      'Service providers that help us host, store, or analyze data under confidentiality obligations.',
      'Legal or regulatory requests when required by law.',
    ],
  },
  {
    title: 'Data Storage and Retention',
    paragraphs: [
      'Your data is stored as long as you maintain an account or as needed to provide the service.',
      'If you delete your account, we will remove or anonymize your personal data, unless we are required to keep certain records for legal reasons.',
    ],
  },
  {
    title: 'Your Choices',
    paragraphs: [
      'You can review and update your profile information in the account settings.',
      'You may request deletion of your account through the feedback page.',
    ],
  },
  {
    title: 'Security',
    paragraphs: [
      'We use reasonable safeguards to protect your data. No method of transmission or storage is fully secure, so we cannot guarantee absolute security.',
    ],
  },
  {
    title: 'Children',
    paragraphs: [
      'The app is not directed to children under 13. If you believe a child has provided personal data, contact us to request deletion.',
    ],
  },
  {
    title: 'Changes to This Policy',
    paragraphs: [
      'We may update this policy from time to time. The latest version will always be available in the app.',
    ],
  },
  {
    title: 'Contact',
    paragraphs: [
      'For privacy-related questions or requests, use the feedback page to reach our team.',
    ],
  },
];

function PrivacyPolicyPage() {
  const theme = useTheme();

  return (
    <Box
      sx={{
        minHeight: '100vh',
        backgroundColor: theme.palette.background.default,
        py: { xs: 3, md: 5 },
      }}
    >
      <Container maxWidth="md">
        <Paper
          elevation={3}
          sx={{
            p: { xs: 3, md: 4 },
            mb: 3,
            borderRadius: 2,
            background: `linear-gradient(135deg, ${theme.palette.background.paper} 0%, ${theme.palette.action.hover} 100%)`,
          }}
        >
          <Typography variant="h3" component="h1" fontWeight={700} gutterBottom>
            Privacy Policy
          </Typography>
          <Typography variant="body1" color="text.secondary" sx={{ maxWidth: 680 }}>
            We value your privacy and want you to understand how your information is handled while
            you train with Kyokushin-Kai.
          </Typography>
          <Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 2 }}>
            Last updated: January 2, 2026
          </Typography>
        </Paper>

        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
          {POLICY_SECTIONS.map((section) => (
            <Paper
              key={section.title}
              elevation={1}
              sx={{
                p: { xs: 3, md: 4 },
                borderRadius: 2,
                backgroundColor: theme.palette.background.paper,
              }}
            >
              <Typography variant="h5" component="h2" fontWeight={600} gutterBottom>
                {section.title}
              </Typography>
              <Divider sx={{ mb: 2 }} />
              {section.paragraphs.map((paragraph, index) => (
                <Typography key={`${section.title}-p-${index}`} variant="body1" paragraph>
                  {paragraph}
                </Typography>
              ))}
              {section.bullets && (
                <Box component="ul" sx={{ pl: 3, mb: 0, mt: 1 }}>
                  {section.bullets.map((bullet) => (
                    <Box component="li" key={`${section.title}-${bullet}`} sx={{ mb: 1 }}>
                      <Typography variant="body2" color="text.secondary">
                        {bullet}
                      </Typography>
                    </Box>
                  ))}
                </Box>
              )}
            </Paper>
          ))}
        </Box>
      </Container>
    </Box>
  );
}

export default PrivacyPolicyPage;
