// file: src/data/model/common.ts
export type ISODateTimeString = string; // e.g. "2025-12-17T16:40:00.000Z"

export type Locale = 'romaji' | 'ja' | 'en' | 'sv';
export type LocalizedText = Partial<Record<Locale, string>>;

/**
 * Opaque IDs generated by your admin backend (UUID/ULID).
 * Never derived from names, so renames are safe.
 */
export type TechniqueId = string;
export type KataId = string;
export type TermId = string;

export type MediaId = string;
export type SourceId = string;

export type GradeId = string;
export type GradingSystemId = string;

export type UserId = string;
export type UserNoteId = string;
export type UserMediaId = string;

/**
 * Lifecycle flags used across canonical entities.
 */
export type PublishStatus = 'draft' | 'published' | 'inactive';